### ISSUE TITLE
roadmap(accordion): aggregation issue

### ISSUE THREAD

**Issue by EvilAlexei** [valor-software/ngx-bootstrap#3128]
### Demos
- [ ] docs(demos): demos should have following structure
   - Quick start
   - Properties
   - Styling
   - Custom content
   - Config
- [x] docs(demos):  decompose `Simple accordion` and rename first section to `Basic` #3616
- [x] docs(demos):  decompose `Disabled` #3619
- [x] docs(demos):  decompose `Dynamic accordion` #3627

### New functionality
- [ ] feat(accordion): Add aria support
- [ ] feat(accordion): Implement key navigation support https://github.com/valor-software/ngx-bootstrap/issues/1675
- [ ] feat(accordion): Implement data attributes service
  - Options
  - Dynamic init/insert
- [ ] feat(accordion): Component custom template
- [ ] feat(collapse): Add animation to open/close events

### Existing features
- [x] feat(accordion): add to "Api Reference" section accordion component #3643
- [ ] feat(accordion): change accordion-heading implementation to `ng-container ` (templateRef, components)
- [ ] feat(docs): fix component styling sections https://github.com/valor-software/ngx-bootstrap/issues/1468

## Component acceptance criteria:
- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
   - ngmodel
   - ngmodel + custom validation
   - reactive forms
   - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes

**Comment by EvilAlexei** [comment]
`(?)` - need more info
