### ISSUE TITLE
roadmap(carousel): aggregation issue

### ISSUE THREAD

**Issue by v1ktoryy** [valor-software/ngx-bootstrap#3232]
### Demos

- [x]  docs(carousel): demos should have following structure
  - Quick start
  - Properties
  - Styling
  - Custom content
  - Config
- [x] docs(carousel): decomopose `Dynamic Slides` #3651
 - Enable/Disable indicator
 - Disable Slide Looping
 - Interval
- [x] docs(carousel): add `Custom content in slides` #3634
- [x] docs(carousel): add demo for `noPause` function #3645
- [x] docs(carousel): add demo for `activeSlideChange` #3677

### New Functionality
- [ ] feat(carousel): add `Aria support`
- [ ] feat(carousel): implement `Key navigation support`
- [ ] feat(carousel): implement `Data attributes service`:
  - Options template replace
  - Dynamic init/insert
- [x] feat(carousel): add custom template for carousel captions https://github.com/valor-software/ngx-bootstrap/issues/1727
- [ ] feat(carousel): add `Right to Left ` function
- [ ] feat(carousel): add `Lazy Load` function
- [ ] feat(carousel): add `Input to remove specific controls` 
- [ ] feat(carousel): add `Animation` https://github.com/valor-software/ngx-bootstrap/issues/281
- [x] feat(carousel): add availability toggle carousel-indicators via property https://github.com/valor-software/ngx-bootstrap/issues/1021
- [ ] feat(carousel): add `Vertical Mode` _(?)_
- [x] feat(carousel): add `Multiple items(in one slide)` _(?)_ https://github.com/valor-software/ngx-bootstrap/issues/965
- [ ] feat(carousel): add `Responsive Uneven sets (infinite)` _(?)_
- [ ] feat(carousel): add `Uneven sets (finite)` _(?)_
- [ ] feat(carousel): add `Center Mode` _(?)_
- [ ] feat(carousel): add `Swipe To Slide` _(?)_ https://github.com/valor-software/ngx-bootstrap/issues/885
- [ ] feat(carousel): add `Vertical Mode with Swipe To Slide` _(?)_
- [ ] feat(carousel): add `FocusOnSelect (Click on any slide to select and make it current slide)` _(?)_

### Existing issues

- [x] fix(carousel): unable to update carousel with dynamic values (needs: reproduce) https://github.com/valor-software/ngx-bootstrap/issues/1954

 _(?)_ - needs refinement

## Component acceptance criteria:

- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
   - ngmodel
   - ngmodel + custom validation
   - reactive forms
   - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
