### ISSUE TITLE
roadmap(progressbar): aggregation issue

### ISSUE THREAD

**Issue by FreeInc** [valor-software/ngx-bootstrap#3234]
## Demos:
- [ ] docs(progressbar): demos should have following structure:
  - Quick start
  - Properties
  - Styling
  - Custom content
  - Config
- [ ] docs(progressbar): Decompose demo Static progress-bar #3570
- [ ] docs(progressbar): add top intend for `Randomize` button in `Dynamic` demo #3735
 - by bootstrap class(es)
 - only for bootstrap4 and check on bootstrap3(already have this intend)
- [ ] docs(progressbar): Add demo Progress-spinner (?)
- [ ] docs(progressbar): Add demo Progress-circle (?)
- [ ] docs(progressbar): Add demo Theming (?)
- [ ] docs(progressbar): Add demo Progress modes (?)
- [ ] docs(progressbar): Add demo Custom forms (?)

## New functionality:
- [ ] feat(progressbar): Add aria support
- [ ] feat(progressbar): Implement data attributes service
    - Options
    - Dynamic init
- [ ] feat(progressbar): Template replace
- [ ] feat(progressbar): Add animation 

## Component acceptance criteria:
- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
  - ngmodel
  - ngmodel + custom validation
  - reactive forms
  - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
