### ISSUE TITLE
roadmap(alerts): aggregation issue

### ISSUE THREAD

**Issue by tarusin** [valor-software/ngx-bootstrap#3235]
### Demos:
- [ ] docs(alerts demos): demos should have following structure
  - Quick start
  - Properties
  - Styling
  - Custom content
  - Config

### New functionality:
- [ ] docs(alerts): add `Alert service(toaster)`
- [ ] docs(alerts): add `Aria support`
- [ ] docs(alerts): add `Data-attributes`
  - Dynamic init
  - Options
- [ ] docs(alerts): add `Template replace`
- [ ] docs(alerts): add `Stackable alerts`
  - Stack few alerts one by one
  - And fade(hide) one by one

### Existing issues
- [ ] fix(alerts): after dismissing alert are not removing from DOM https://github.com/valor-software/ngx-bootstrap/issues/3608

## Component acceptance criteria:
- [ ] Adding to project / Quick star
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
  - ngmodel
  - ngmodel + custom validation
  - reactive forms
  - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
