### ISSUE TITLE
roadmap(button): aggregation issue

### ISSUE THREAD

**Issue by artolshansky** [valor-software/ngx-bootstrap#3236]
### Demos
- [ ] docs(button): demos should have following structure
  - Quick start
  - Properties
  - Styling
  - Custom content
  - Config
- [ ] docs(button): decompose `Single button` demo #3663
  - add demo for `btnCheckboxTrue` & `btnCheckboxFalse` properties
  - rename `Single button` to `Basic`
- [ ] docs(button): decompose `Radio & Uncheckable Radio` demo #3581

### New functionality
- [ ] feat(button): Add aria support
- [ ] feat(button): Implement key navigation support
- [ ] feat(button): Implement data attributes service
  - Options
  - Dynamic init
- [ ] feat(button): Component custom template
- [ ] feat(button): Button loading state
- [ ] feat(button): Add hover/click animation

### Existing features
- [ ] feat(button): Button group functionality
- [ ] feat(button): remove for inputs and documentation `value`

### Existing issues
- [x] fix(buttons): btnRadio does not work with reactive forms in versions >1.7.1 https://github.com/valor-software/ngx-bootstrap/issues/2581

## Component acceptance criteria:
- [ ] Adding to project / Quick star
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
  - ngmodel
  - ngmodel + custom validation
  - reactive forms
  - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
