### ISSUE TITLE
roadmap(pagination): aggregation issue

### ISSUE THREAD

**Issue by IraErshova** [valor-software/ngx-bootstrap#3237]
### Demos
- [ ] docs(popover): demos should have following structure
  - Quick start
  - Properties
  - Styling
  - Custom content
  - Config
- [ ] docs(pagination): rename `Default` section to `Basic` #3680
- [ ] docs(pagination): Add demo for disabled and active states #3688
- [ ] docs(pagination): Add demo for content switching #3771
- [ ] docs(pagination): decompose States & Limits section #3763
- [ ] docs(pagination): add demo with list https://github.com/valor-software/ngx-bootstrap/issues/450

### New functionality
- [ ] feat(pagination): Add aria support
- [ ] feat(pagination): Implement data attributes service
  - Options
  - Dynamic init/insert
- [ ] feat(pagination): Add animation to change page events
- [ ] feat(pagination): Add component custom template
- [ ] feat(pagination): add ability to change the pager template in the pagination component https://github.com/valor-software/ngx-bootstrap/issues/2044
- [ ] feat(pagination): add functionality of sending request instead of changing page directly by click https://github.com/valor-software/ngx-bootstrap/issues/3376
- [ ] feat(pagination): add event for firing when amount of pages decreases (now pageChanged event is fired) https://github.com/valor-software/ngx-bootstrap/issues/2175

### Existing issues
- [ ] fix(pagination): with async piped ngModel totalItemCount$ and currentPage$ are out of sync https://github.com/valor-software/ngx-bootstrap/issues/3289

## Component acceptance criteria:
- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
  - ngmodel
  - ngmodel + custom validation
  - reactive forms
  - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
