### ISSUE TITLE
roadmap(collapse): aggregation issue

### ISSUE THREAD

**Issue by ghost** [valor-software/ngx-bootstrap#3238]
###  **Demos**

- [ ] docs(collapse): demos should have following structure
    - Quick start
    -  Properties
    -  Styling
    - Custom content
    - Config
- [ ] docs(collapse): decompose `Basic` demo #3789
- [ ] docs(collapse): add `hide method` demo #3591
- [ ] docs(collapse): add `show method` demo #3591

### **New functionality**

- [ ]  feat(Collapse): add aria support
- [ ]  feat(Collapse): implement data-attributes 
    - options
    - dynamic init/insert
- [ ]   feat(Collapse):  component template replace
- [ ]  feat(Collapse): add animation
- [ ]  feat(Collapse): add vertically/horizontally toggle collaps 
- [ ]  feat(Collapse): add custom spring configuration
- [ ]  feat(Collapse): add nested collapse (?)
- [ ] feat(Collapse): add auto-unmount, when closed (?)
- [ ] feat(Collapse): add trigger multiple collapse elements (?)
- [ ] feat(collapse): add pickup collapsed height property https://github.com/valor-software/ngx-bootstrap/issues/2578

### Existing issues

- [ ] fix(collapse): switching CSS property when use CollapseModule https://github.com/valor-software/ngx-bootstrap/issues/2473

## **Component acceptance criteria:**

- [ ] Adding to project / Quick start
    - note for system.js
    - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
    - ngmodel
    - ngmodel + custom validation
    - forms
    - reactive forms + custom validation
- [ ]  Each demo sample should have test
- [ ] Styling
    - via parent component
    - via global css
- [ ]  Accessibility
    - Aria
    - Keyboard navigation
    - Mobile 
- [ ] Animations support (from animation component)
- [ ] Overriding default config
    - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
