### ISSUE TITLE
roadmap(dropdown): aggregation issue

### ISSUE THREAD

**Issue by EvilAlexei** [valor-software/ngx-bootstrap#3253]
### Demos
- [ ] docs(dropdown): demos should have following structure
   - Quick start
   - Properties
   - Styling
   - Custom content
   - Config
- [x] docs(dropdown): add demo for disabled item inside menu #3783 
- [x] docs(dropdown): add demo for item custom HTML #3801
- [x] docs(dropdown): add demo for menu dividers #3788
- [x] docs(dropdown): decompose `Single button dropdowns` demo #3799
 - Remove divider and separated link
 - Rename `Single button dropdowns` to `Basic`
- [x] docs(dropdown): decompose `Menu alignment` demo -> divider and separated link #3788
- [x] docs(dropdown): decompose `Split button dropdowns` demo -> divider and separated link #3788
- [x] docs(dropdown): decompose `Manual triggers` demo -> divider and separated link #3788
- [x] docs(dropdown): decompose `Disabled menu` demo #3797
 - divider and separated link
 - rename class on button "dropdownToggle" to "dropdown-toggle"
- [x] docs(dropdown): decompose `Nested dropdowns (experimental)` demo -> divider and separated link #3788
- [x] docs(dropdown): decompose `Append to body` demo #3794 
 - divider and separated link
 - rename class on button "dropdownToggle" to "dropdown-toggle"
- [x] docs(dropdown): decompose `Dropup variation` demo -> divider and separated link #3790 
- [x] docs(dropdown): demo for `isOpenChange` options #3777
- [x] docs(dropdown): demo for `autoClose` #3781
- [x] docs(dropdown): demo for `onHidden`/`onShown` #3774

### New functionality
- [x] feat(dropdown): add option to set placement
- [ ] feat(dropdown): Add aria support
- [ ] feat(dropdown): Implement key navigation support
- [ ] feat(dropdown): Implement data attributes service
  - Options
  - Dynamic init/insert
- [ ] feat(dropdown): Component custom template
- [ ] feat(dropdown): Add animation to open/close events
- [ ] feat(dropdown): allow tab in tabset to be a dropdown menu https://github.com/valor-software/ngx-bootstrap/issues/1888
- [ ] feat(dropdown): add mouseleave event as default trigger for closing dropdown https://github.com/valor-software/ngx-bootstrap/issues/2677

### Existing issues
- [ ] fix(dropdown) autoClose on outside-click doesn't work with unallowed autoClose on inside-click https://github.com/valor-software/ngx-bootstrap/issues/1933
- [ ] fix(dropdown): performance problems with multiple dropdowns https://github.com/valor-software/ngx-bootstrap/issues/2172
- [ ] fix(dropdown): dropdown does not take into account page boundaries https://github.com/valor-software/ngx-bootstrap/issues/2998
- [ ] fix(dropdown): dropdowns with hover trigger need to be clicked twice for first time appearing at mobile and tablet devices https://github.com/valor-software/ngx-bootstrap/issues/3048
- [ ] docs(dropdown): dropdowns placement doesn't affect anything if dropdown is shown inline https://github.com/valor-software/ngx-bootstrap/issues/3370
- [ ] fix(dropdown): Anchor based dropdown does not close if triggers is set https://github.com/valor-software/ngx-bootstrap/issues/3287
- [x] open dropdown inside modal (needs: reproduce. not sure, that this is issue) https://github.com/valor-software/ngx-bootstrap/issues/3453

## Component acceptance criteria:
- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
   - ngmodel
   - ngmodel + custom validation
   - reactive forms
   - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes

**Comment by valorkin** [comment]
@zwenza dropdown has no integration with inputs or forms, so it should not support forms
most probably you meant typeahead or select

PS this 2 comments are not relates to roadmap and will be removed soon

**Comment by zwenza** [comment]
@valorkin thanks for the fast answer.
Typeahead isn't exactly what i need. Where do I find the select component you mentioned ?

**Comment by valorkin** [comment]
ng2-select is a package for it, but its kinda old
New version is WIP

**Comment by zwenza** [comment]
Does ng2-select support Bootstrap4 ?

I don't quite understand the purpose of the dropdown if it doesn't support any form/input. 
When does it make sense to use the ngx-bootstrap dropdown ?

**Comment by valorkin** [comment]
When you need dropdowns - you are using dropdowns
Always yours, Cap

**Comment by zwenza** [comment]
I just wrote my own wrapper around it so I can use it with my forms :)

Thanks anyway
