### ISSUE TITLE
roadmap(tooltips): aggregation issue

### ISSUE THREAD

**Issue by tarusin** [valor-software/ngx-bootstrap#3254]
## Demos:
- [ ] docs(tooltips demos): demos should have following structure
  - Quick start
  - Properties
  - Styling
  - Custom content
  - Config
- [ ] docs(tooltips demos): add demo for toggle method in Manual triggering demo #3767
- [ ] docs(tooltips demos): clarify Dynamic Content demo #3769 
 - Separate options in description
- [ ] docs(tooltips demos): rename demo `Four directions` to `Placement` #3764

## New functionality:
- [ ] docs(tooltips): add `Aria support`
- [ ] docs(tooltips): add `Data-attributes`
  - Dynamic init
  - Options
- [ ] docs(tooltips): add `Template replace`
- [ ] docs(tooltips): add `Animation`

## Existing issues
- [ ] fix(tooltip): setInterval running out of angular zone is triggering ngZone.onStable in component-loader.class.js https://github.com/valor-software/ngx-bootstrap/issues/2632
- [x] fix(tooltip): tooltips with delay continue displaying even if not hovering after timeout https://github.com/valor-software/ngx-bootstrap/issues/3038
- [ ] fix(tooltip): tooltips while zoomed can cause tab to crash https://github.com/valor-software/ngx-bootstrap/issues/3047
- [ ] fix(tooltip): tooltip flickering when hover the mouse on the border on the tooltip position https://github.com/valor-software/ngx-bootstrap/issues/3075
- [ ] fix(tooltip): if host element was removed via click, tooltip will persist https://github.com/valor-software/ngx-bootstrap/issues/3142
- [ ] fix(tooltip): first-opened tooltip has wrong placement (needs: reproduce) https://github.com/valor-software/ngx-bootstrap/issues/3310
- [ ] fix(tooltip demo): tooltip doesn't appear at example Dismiss on next click for Safari browser https://github.com/valor-software/ngx-bootstrap/issues/3294

## Component acceptance criteria:
- [ ] Adding to project / Quick star
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
  - ngmodel
  - ngmodel + custom validation
  - reactive forms
  - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
