### ISSUE TITLE
roadmap(popover): aggregation issue

### ISSUE THREAD

**Issue by artolshansky** [valor-software/ngx-bootstrap#3255]
### Demos
- [ ] docs(popover): demos should have following structure
  - Quick start
  - Properties
  - Styling
  - Custom content
  - Config
- [ ] docs(popover): rename `Four directions` demo to `Placement` #3811 
- [ ] docs(popover): clarify `Dynamic Content` demo #3834
 - Separate options in description
- [ ] docs(popover): fix `Append to body` demo #3837
 - fix html markup for bs4
 - for bs4 make more visible the problem with default popover (like for bs3, add indents maybe),
   example in tooltips, same demo
- [ ] docs(popover): add more complicated(new) example for `Custom triggers` demo  #3828
- [ ] docs(popover): add demo for `toggle` method in `Manual triggering` demo #3818
- [ ] docs(popover): add effects/animations demo #3845
- [ ] docs(popover): add `isOpen` input demo #3795
- [ ] docs(popover): add `popoverContext` input demo #3808 
- [ ] docs(popover): add `onHidden`&`onShown` output demo #3807 

### New functionality
- [ ] feat(popover): Add aria support
- [ ] feat(popover): Implement data attributes service
  - Options
  - Dynamic init
- [ ] feat(popover): Component custom template
- [ ] feat(popover): Add show/hide animations
- [ ] feat(popover): add more positional options for popover (for example, ‘bottom-left’) https://github.com/valor-software/ngx-bootstrap/issues/1750
- [ ] feat(popover): add functionality of displaying/attaching popover without using the directive https://github.com/valor-software/ngx-bootstrap/issues/1983
- [ ] feat(popover): add functionality of displaying popoverTitle as HTML https://github.com/valor-software/ngx-bootstrap/issues/2577
- [ ] feat(popover): allow passing custom data to show() method for popovers https://github.com/valor-software/ngx-bootstrap/issues/2853

### Existing issues
- [ ] docs(popover): add detailed description of triggers for popover module https://github.com/valor-software/ngx-bootstrap/issues/1772
- [ ] fix(popover): "auto" position is not working correctly https://github.com/valor-software/ngx-bootstrap/issues/2796
- [ ] fix(popover): popover with custom template crashes in IE (needs: info) https://github.com/valor-software/ngx-bootstrap/issues/2994
- [ ] fix(demo popover): for bootstrap 4 popovers with triggers: 'focus' flickers in time of second click at Safari https://github.com/valor-software/ngx-bootstrap/issues/3314
- [ ] fix(demo popover): all popovers, that are placed near left side of demo are cutted by viewport borders, if left side menu is not shown https://github.com/valor-software/ngx-bootstrap/issues/3303

## Component acceptance criteria:
- [ ] Adding to project / Quick star
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
  - ngmodel
  - ngmodel + custom validation
  - reactive forms
  - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
