### ISSUE TITLE
roadmap(sortable): aggregation issue

### ISSUE THREAD

**Issue by v1ktoryy** [valor-software/ngx-bootstrap#3256]
### Demos

- [ ] docs(sortable): demos should have following structure
  - Quick start
  - Properties
  - Styling
  - Custom content
  - Config
- [ ] docs(sortable): rename `String items` to `Basic` #3824
- [ ] docs(sortable): rename `Custom item template`  to `Custom item content` #3830

### New Functionality

- [ ] feat(sortable): add `Aria support`
- [ ] feat(sortable): Implement data attributes service
  - Options template replace
  - Dynamic init/insert
- [ ] feat(sortable): add `Animation` effects to sort items (including demos)
- [ ] feat(sortable): rework sortable _(?)_
- [ ] feat(sortable): add functionality of using sortable inside sortable https://github.com/valor-software/ngx-bootstrap/issues/1681
- [ ] feat(sortable): add support for mobile and tablet platform https://github.com/valor-software/ngx-bootstrap/issues/1835

### Existing features

- [ ] feat(sortable): add  `Draggable-item` component to API reference section

### Existing issues
- [ ] fix(sortable): sortable should be refreshed when a new item is added to the array https://github.com/valor-software/ngx-bootstrap/issues/1716
- [ ] fix(sortable): two sortables with the same model infinitely loop rather than erroring out https://github.com/valor-software/ngx-bootstrap/issues/1828

## Component acceptance criteria:

- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
   - ngmodel
   - ngmodel + custom validation
   - reactive forms
   - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes

**Comment by lterfloth** [comment]
Any information on this yet?
