### ISSUE TITLE
roadmap(modal): aggregation issue

### ISSUE THREAD

**Issue by EvilAlexei** [valor-software/ngx-bootstrap#3258]
### Demos
- [ ] docs(modal): demos should have following structure
   - Quick start
   - Properties
   - Styling
   - Custom content
   - Config
- [ ] docs(modal): add demo for scrolling long content #3589
- [ ] docs(modal): add demo for modal with tooltips and popovers #3817
- [ ] docs(modal): passing data from the child modal to the parent https://github.com/valor-software/ngx-bootstrap/issues/2330
- [ ] docs(modal): decompose `Options` demo #3583

### New functionality
- [ ] feat(modal): add aria support
- [ ] feat(modal): implement key navigation support
- [ ] feat(modal): implement data attributes service
  - Options
  - Dynamic init/insert
- [ ] feat(modal): component custom template
- [ ] feat(modal): `handleUpdate` method for readjust the modal’s position
- [ ] feat(modals): add an options to append modals to element https://github.com/valor-software/ngx-bootstrap/issues/731
- [ ] feat(modal): change modal's z-index manually, without modifying the dist CSS https://github.com/valor-software/ngx-bootstrap/issues/2331
- [ ] feat(modal): initialize and create all component variables before OnInit https://github.com/valor-software/ngx-bootstrap/issues/2530
- [ ] feat(modal): add possibility of dynamic changing class of a modal when using BsModalRef https://github.com/valor-software/ngx-bootstrap/issues/2824
- [ ] feat(modal): add functionality for identifying which modal triggered the events https://github.com/valor-software/ngx-bootstrap/issues/2917
- [ ] feat(modal): add functionality of executing a function before closing the modal https://github.com/valor-software/ngx-bootstrap/issues/3231
- [ ] feat(modal): add declaration of checkScrollbar in modal https://github.com/valor-software/ngx-bootstrap/issues/3411

### Existing issues
- [ ] docs(modal): add documentation for the focus config option for modals https://github.com/valor-software/ngx-bootstrap/issues/1597
- [ ]  feat(modals) add unit test opening ng modal window https://github.com/valor-software/ngx-bootstrap/issues/2492
- [ ] fix(modal): focus coming out of Modal after pressing Tab key https://github.com/valor-software/ngx-bootstrap/issues/1819
- [ ] fix(modal): modal does not properly work in a lazy loaded module https://github.com/valor-software/ngx-bootstrap/issues/2356
- [ ] fix(modal): modal from component running both animations, closing then opening (needs: reproduce) https://github.com/valor-software/ngx-bootstrap/issues/2674 
- [ ] fix(modal): click function inside modal on internet explorer not working (needs: reproduce) https://github.com/valor-software/ngx-bootstrap/issues/2818
- [ ] feat(modal): add example of getting a return value from a modal https://github.com/valor-software/ngx-bootstrap/issues/2721
- [ ] fix(demo modals): after opening any modal and pressing Esc button, browser minimize and only after that modal dissappears https://github.com/valor-software/ngx-bootstrap/issues/3313

## Component acceptance criteria:
- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
   - ngmodel
   - ngmodel + custom validation
   - reactive forms
   - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
