### ISSUE TITLE
roadmap(timepicker): aggregation issue

### ISSUE THREAD

**Issue by artolshansky** [valor-software/ngx-bootstrap#3265]
### Demos
- [ ] docs(timepicker): demos should have following structure
  - Quick start
  - Properties
  - Styling
  - Custom content
  - Config
- [ ] docs(timepicker): rename `Timepicker` demo to `Basic` #3732
- [ ] docs(timepicker): decompose `Dynamic` demo -> remove validation for clear btn #3849
- [ ] docs(timepicker): decompose `Mouse wheel and Arrow keys` demo #3546
- [ ] docs(timepicker): add `meridians` property demo #3726
- [ ] docs(timepicker): add `secondsStep` property demo #3569
- [ ] docs(timepicker): add `showSpinners` property demo #3574
- [ ] docs(timepicker): add `isValid` output demo #3612
- [ ] docs(timepicker): at Disabled Timepicker example input fields are highlighted after click, even if they are disabled #3371 
- [ ] docs(timepicker): Min-max demo example. When user once choose unavailable PM time, AM/PM button stops working #3288, #3549 

### New functionality
- [ ] feat(timepicker): Add aria support
- [ ] feat(timepicker): Implement key navigation support 
- [ ] feat(timepicker): Implement data attributes service
  - Options
  - Dynamic init
- [ ] feat(timepicker): Component custom template
- [ ] feat(timepicker): Add ability to set readonly/disabled state #3602
- [ ] feat(timepicker)(datepicker): add keys support to DateTimePicker https://github.com/valor-software/ngx-bootstrap/issues/1455
- [ ] feat(timepicker): Add validation for timepicker #3549
- [ ] feat(timepicker): showMinutes flag check in timepicker component https://github.com/valor-software/ngx-bootstrap/issues/2430
- [ ] feat(timepicker): add possibility of using Timepicker as a popup https://github.com/valor-software/ngx-bootstrap/issues/2616
- [ ] feat(timepicker): add functionality of getting selected time without using ngModel (by emitting output event when time changes) https://github.com/valor-software/ngx-bootstrap/issues/3368

### Existing issues
- [ ] fix(timepicker): TimePicker shows 01:00 if date is undefined and showMeridian is false https://github.com/valor-software/ngx-bootstrap/issues/2614
- [ ] fix(timepicker): keyboard/text changes to Timepicker "minutes" swaps AM/PM https://github.com/valor-software/ngx-bootstrap/issues/3132
- [ ] fix(timepicker): 11:59PM to 12:00AM pushes the "date" a day forward and vice-versa https://github.com/valor-software/ngx-bootstrap/issues/3139

## Component acceptance criteria:
- [ ] Adding to project / Quick star
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
  - ngmodel
  - ngmodel + custom validation
  - reactive forms
  - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
