### ISSUE TITLE
roadmap(tabs): aggregation issue

### ISSUE THREAD

**Issue by tarusin** [valor-software/ngx-bootstrap#3267]
## Demos:
- [ ] docs(tabs): demos should have following structure
  - Quick start
  - Properties
  - Styling
  - Custom content #3548
  - Config
- [ ] docs(tabs): make tabs content(tab-pane) looks nice #3642
- [ ] docs(tabs): decompose `Dynamic tabs` -> remove  disabled tab #3637
- [ ] docs(tabs): decompose `Manual selection` #3545 
- [ ] docs(tabs): decompose `Static tabs` #3601
- [ ] docs(tabs): add demo for select event #3664
## New functionality:
- [ ] docs(tabs): add `Aria support`
- [ ] docs(tabs): add `Data-attributes`
  - Dynamic init
  - Options
- [ ] docs(tabs): add `Template replace`
- [ ] docs(tabs): add `Animation`
- [ ] feat(tabs): add functionality of canceling a tab removal https://github.com/valor-software/ngx-bootstrap/issues/786
- [ ] feat(tabs): add tab opened event https://github.com/valor-software/ngx-bootstrap/issues/1066
- [ ] feat(tabs): add ability to prevent tab selection https://github.com/valor-software/ngx-bootstrap/issues/1502
- [ ] feat(docs): add dynamic tab heading sample https://github.com/valor-software/ngx-bootstrap/issues/1487
- [ ] feat(tabs): remove ngTransclude https://github.com/valor-software/ngx-bootstrap/issues/1314
- [ ] feat(tabs): add animation that makes tab content slide when changing tab https://github.com/valor-software/ngx-bootstrap/issues/1347
- [ ] feat(tabs): adding customClass selector to tabset https://github.com/valor-software/ngx-bootstrap/issues/1508
- [ ] feat(tabs): add access to the (click) functionality with the tabs https://github.com/valor-software/ngx-bootstrap/issues/2966
- [ ] feat(tabs): add support of Vertical tabs https://github.com/valor-software/ngx-bootstrap/issues/3033

## Existing issues
- [ ] fix(tabs): order not working with ngIf\dynamic directives https://github.com/valor-software/ngx-bootstrap/issues/823
- [ ] fix(tabs): all tabs are showing (initiated and added to the DOM) even if no tab is selected https://github.com/valor-software/ngx-bootstrap/issues/1422
- [ ] fix(tabs): accessibility attributes are missing in Tabset component https://github.com/valor-software/ngx-bootstrap/issues/2706

## Component acceptance criteria:
- [ ] Adding to project / Quick star
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
  - ngmodel
  - ngmodel + custom validation
  - reactive forms
  - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
