### ISSUE TITLE
roadmap(datepicker): aggregation issue

### ISSUE THREAD

**Issue by EvilAlexei** [valor-software/ngx-bootstrap#3340]
### Demos
- [ ] docs(datepicker): demos should have following structure
   - Quick start
   - Properties
   - Styling
   - Custom content
   - Config
- [ ] docs(datepicker): add demo for supported formats, based on moment.js(1:1) #3590
- [ ] docs(datepicker): decompose `Basic` demo #3669
 - remove presetting dates for datepicker and daterangepicker
 - add demo for pre-setting date by bsValue, [(ngModel)] etc.
- [x] docs(datepicker): add demo for `bsConfig` #3632
- [x] docs(datepicker): add demo for disabled state #3827
- [x] docs(datepicker): add demo for `isOpen` state #3640
- [x] docs(datepicker): add demo for `outsideClick` option #3636
- [x] docs(datepicker): add demo for datepicker placement #3624
- [x] docs(datepicker): add demo for different triggers #3729
- [x] docs(datepicker): add demo for `bsValueChange` output #3614
- [x] docs(datepicker): add demo for `onHidden/onShown` outputs #3607 
- [x] docs(datepicker): add demo for `Show/Hide/Toggle` events #3603
- [x] docs(datepicker): add demo for `setConfig` #3626
- [ ] docs(datepicker): add sample with import() https://github.com/valor-software/ngx-bootstrap/issues/2679

### New functionality
- [ ] feat(datepicker): add aria support
- [ ] feat(datepicker): implement key navigation support
 - existing feat request for key navigation https://github.com/valor-software/ngx-bootstrap/issues/1300
- [ ] feat(datepicker): implement data attributes service
  - Options
  - Dynamic init/insert
- [ ] feat(datepicker): component custom template
- [ ] feat(datepicker): add validation
 - existing feat request https://github.com/valor-software/ngx-bootstrap/issues/3417
- [ ] feat(datepicker): add option to set starting weekday via bs-config
- [ ] feat(datepicker): reseting min and max boundaries will reset it in datepicker
- [ ] feat(datepicker): add new themes to datepicker
- [ ] feat(datepicker): add old datepicker as new theme
- [ ] feat(datepicker): add option to disable/enable centering datepicker/daterangepicker on mobile
- [ ] feat(datepicker): enable timepicker and custom dates in datepicker 
 - existing feat request for DateTimePicker: https://github.com/valor-software/ngx-bootstrap/issues/551
 - existing feat request of initing datepicker with array of enabled dates https://github.com/valor-software/ngx-bootstrap/issues/1821
- [ ] feat(datepicker): add option to set placeholder with date format
- [ ] feat(datepicker): add listening to the change of month property https://github.com/valor-software/ngx-bootstrap/issues/1153
- [ ] feat(datepicker): Add support for disabling weekends https://github.com/valor-software/ngx-bootstrap/issues/1657
- [ ] feat(datepicker): add possibility of showing only the year and month view https://github.com/valor-software/ngx-bootstrap/issues/2627
- [ ] feat(datepicker): provide an option for custom years math https://github.com/valor-software/ngx-bootstrap/issues/3070
- [ ] feat(datepicker): add possibility of keeping current date always highlighted regardless of the selected date https://github.com/valor-software/ngx-bootstrap/issues/3192
- [ ] feat(datepicker): change default trigger from click to focus in DatePicker https://github.com/valor-software/ngx-bootstrap/issues/3194
- [ ] feat(datepicker): add customClass option to the new version of datepicker https://github.com/valor-software/ngx-bootstrap/issues/2848
- [ ] feat(datepicker): ability to select multiple individual days https://github.com/valor-software/ngx-bootstrap/issues/3240
- [ ] feat(datepicker): add new event triggered after selecting first date https://github.com/valor-software/ngx-bootstrap/issues/3348
- [ ] feat(datepicker, daterangepicker): autoClose config https://github.com/valor-software/ngx-bootstrap/issues/3447
- [ ] feat(datepicker): add possibility of using fixed datepicker zone (UTC) https://github.com/valor-software/ngx-bootstrap/issues/3440
- [ ] feat(daterangepicker): add validation for manual input daterange https://github.com/valor-software/ngx-bootstrap/issues/3498

## Existing issues
- [ ] fix(datepicker): definelocale without additional parameter causes exception https://github.com/valor-software/ngx-bootstrap/issues/2693
- [ ] fix(datepicker): input validator is not called until a date is first chosen https://github.com/valor-software/ngx-bootstrap/issues/2727
- [ ] fix(datepicker): delete input field date and pick a new date not working https://github.com/valor-software/ngx-bootstrap/issues/2996
- [ ] fix(datepicker): double tap required to select a date with the datepicker on ios https://github.com/valor-software/ngx-bootstrap/issues/2810
- [ ] fix(datepicker): lag on datepicker in a modal re-alignment after scrolling https://github.com/valor-software/ngx-bootstrap/issues/2993
- [ ] fix(datepicke)r: bs-datepicker dies after abusive use of enter or space keys https://github.com/valor-software/ngx-bootstrap/issues/3133
- [x] fix(datepicker): support angular@5.2's 'fullTemplateTypeCheck' https://github.com/valor-software/ngx-bootstrap/issues/3455
- [ ] fix(demo datepicker): when date- or datepangepicker popup is open, page under it still scrollable at mobile devices https://github.com/valor-software/ngx-bootstrap/issues/3300
- [ ] fix(demo datepicker): on mobile platform date- and daterangepicker appears right above output, no possibility to enter or edit it manually https://github.com/valor-software/ngx-bootstrap/issues/3301
- [ ] fix(demo datepicker): for width less than 1300px data in output field for daterangepicker is cutted at locales example https://github.com/valor-software/ngx-bootstrap/issues/3302
- [ ] question(datepicker): Inline calendar click event https://github.com/valor-software/ngx-bootstrap/issues/3410

## Component acceptance criteria:
- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
   - ngmodel
   - ngmodel + custom validation
   - reactive forms
   - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes

**Comment by kgupta1988** [comment]
Just being curious, when can we get these features for use?

**Comment by valorkin** [comment]
We start to work on this issues list as soon as v2 will be released

**Comment by stefanradivojevic** [comment]
Hi guys, this one is really important to me:
 

> fix(datepicker): double tap required to select a date with the datepicker on ios #2810 

Can I get any estimation of it? Weeks, months, maybe years? :) Thank you a lot.

**Comment by pepemiso16** [comment]
Hi, I just want to ask where can we be able to get the updates for this issue:
 fix(datepicker): delete input field date and pick a new date not working #2996 
Badly needed this one. Thanks.

**Comment by amorenew** [comment]
I hope this item get more priority:  feat(datepicker): component custom template
and if possible I hope you could add horizontal scroll 
thanks

**Comment by mahesh5b5** [comment]
Need date picker with disabled weekends..

**Comment by srikanthpoli** [comment]
is there any other way to achieve this?

**Comment by meshubh** [comment]
Hi

By when can we expect the accessibility(Keyboard navigation) feature to be implemented?
@EvilAlexei
