### ISSUE TITLE
roadmap(typeahead): aggregation issue

### ISSUE THREAD

**Issue by EvilAlexei** [valor-software/ngx-bootstrap#3342]
### Demos
- [ ] docs(typehead): demos should have following structure
   - Quick start
   - Properties
   - Styling
   - Custom content
   - Config
- [ ] docs(typehead): rename demo `Static array` to `Basic` #3657
- [ ] docs(typehead): (?) add demo for basic local data autocomplete
- [ ] docs(typehead): add demo for container (append to body) #3737 
- [ ] docs(typehead): add demo `Styling` with sizing by custom class #3835
- [ ] docs(typehead): add demo for using with forms #3748
- [ ] docs(typehead): add demo for `optionsListTemplate` #3753 
- [ ] docs(typehead): add demo for `typeaheadLatinize` #3666 
- [ ] docs(typehead): add demo for `typeaheadSingleWords` #3843
- [ ] docs(typehead): add demo for `typeaheadPhraseDelimiters` #3847
- [ ] docs(typehead): add demo for `typeaheadWordDelimiters` #3662
- [ ] docs(typehead): add demo for `typeaheadWaitMs` #3659
- [ ] docs(typehead): add demo for `typeaheadLoading` output #3694 
- [ ] docs(typehead): add demo for `typeaheadNoResults` output #3690
- [ ] docs(typehead): add demo for `typeaheadOnBlur` output #3686
- [ ] docs(typehead): add demo for `typeaheadOnSelect` output #3681 
- [ ] docs(typeahead): edit documentation for typeahead for making it more clear https://github.com/valor-software/ngx-bootstrap/issues/2986
- [ ] docs(typeahead): add example of using typeahead with optionListTemplate and typeaheadItemTemplate to demo https://github.com/valor-software/ngx-bootstrap/issues/3081

### New functionality
- [ ] feat(typehead): add aria support
- [ ] feat(typehead): implement key navigation support
- [ ] feat(typehead): implement data attributes service
  - Options
  - Dynamic init/insert
- [ ] feat(typehead): component custom template
- [ ] feat(typehead): add option to set menu alignment
- [ ] feat(typehead): (?) add option for object as ngModel
- [ ] feat(typehead): (?) add custom data provider
- [ ] feat(typehead): (?) add fuzzy matching / custom match functions
- [ ] feat(typehead): (?) add autocomplete input masks ( + Integration with Datepicker & Timepicker)
- [ ] feat(typehead): (?) add multi-select option
- [ ] feat(typehead): (?) add images Support (advanced example)
- [ ] feat(typehead): (?) add custom selections (ability to create new options for the data set.)
- [ ] feat(typehead): (?) add custom filtering: case sensetive/filter by additional string info
- [ ] feat(typehead): (?) add pagination for performance, use limits
- [ ] feat(typeahead): typeahead list span entire length of input https://github.com/valor-software/ngx-bootstrap/issues/190
- [ ] feat(typeahead): custom filter function https://github.com/valor-software/ngx-bootstrap/issues/479
- [ ] feat(typeahead): add accessibility attributes https://github.com/valor-software/ngx-bootstrap/issues/582
- [ ] feat(typeahead): add using multiple sets of results at typeahead https://github.com/valor-software/ngx-bootstrap/issues/794
- [ ] feat(typeahead): support multiple search field values https://github.com/valor-software/ngx-bootstrap/issues/1352
- [ ] feat(typeahead): add support of multi-select https://github.com/valor-software/ngx-bootstrap/issues/940
- [ ] feat(typeahead): add footer to typeahead dropdown https://github.com/valor-software/ngx-bootstrap/issues/1407
- [ ] feat(typeahead): add possibility of canceling ongoing requests when a new request is sent https://github.com/valor-software/ngx-bootstrap/issues/1626
- [ ] feat(typeahead): optionally do not hide the results on blur https://github.com/valor-software/ngx-bootstrap/issues/2059
- [ ] feat(typeahead): change onChange event handler from keyup to keydown https://github.com/valor-software/ngx-bootstrap/issues/2000
- [ ] feat(typeahead): Handling array of objects containing value/label pairs https://github.com/valor-software/ngx-bootstrap/issues/2335
- [ ] feat(typeahead): add possibility of customizing matching function https://github.com/valor-software/ngx-bootstrap/issues/2514
- [ ] feat(typeahead): add header in the typeahead dropdown https://github.com/valor-software/ngx-bootstrap/issues/2846

## Existing issues
- [ ] fix(typeahead): typeahead with initial object value displays [object Object] instead of default value https://github.com/valor-software/ngx-bootstrap/issues/749
- [ ] fix(typeahead): it is not possible to NOT select any option using keys for submit https://github.com/valor-software/ngx-bootstrap/issues/1281
- [ ] docs(typeahead): add example of using distinctUntilChanged with TYPEAHEAD https://github.com/valor-software/ngx-bootstrap/issues/1164
- [ ] fix(typeahead): typeahead focus obtained again after leaving the control https://github.com/valor-software/ngx-bootstrap/issues/1884
- [ ] fix(typeahead): Typeahead, Observable error callback. When API call fails, application stops working https://github.com/valor-software/ngx-bootstrap/issues/1956
- [ ] fix(typeahead): typeahead prepareMatches method doesn't check for undefined observables https://github.com/valor-software/ngx-bootstrap/issues/2519
- [ ] fix(typeahead): typeaheadLatinize works only if last letter has an accent https://github.com/valor-software/ngx-bootstrap/issues/2912
- [ ] fix(typeahead): Typeahead with typeaheadMinLength 0 and placeholder requires two clicks for selecting an item in IE https://github.com/valor-software/ngx-bootstrap/issues/3124
- [ ] question(typeahead): is it possible only allow typeahead selection from list https://github.com/valor-software/ngx-bootstrap/issues/1849

## Component acceptance criteria:
- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
   - ngmodel
   - ngmodel + custom validation
   - reactive forms
   - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes

**Comment by i1990jain** [comment]
when can we see this in action
* possibility of customizing matching function #2514
