### ISSUE TITLE
roadmap(ngx-bootstrap): aggregation issue with feature requests of new components, docs; issues with build and demo

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3466]
### Demos and docs
- [ ] docs(migration): add docs how to migrate from ngx-bootstrap 1.9.x to 2.0.x https://github.com/valor-software/ngx-bootstrap/issues/3022

### New functionality
- [ ] feat(sidenav, menubar): add new components sidenav and menubar https://github.com/valor-software/ngx-bootstrap/issues/77
- [ ] feat(navbar): Support for bootstrap navbar https://github.com/valor-software/ngx-bootstrap/issues/540
- [ ] feat(animations): add animations to all components https://github.com/valor-software/ngx-bootstrap/issues/801
- [ ] feat(plunker): create plunker for each demo https://github.com/valor-software/ngx-bootstrap/issues/970
- [ ] feat(stacked-pills): add new component https://github.com/valor-software/ngx-bootstrap/issues/997
- [ ] feat(media queries): add Media Query Service https://github.com/valor-software/ngx-bootstrap/issues/1154
- [ ] feat(google closure): add google closure compiler support https://github.com/valor-software/ngx-bootstrap/issues/1988
- [ ] feat(sticky directive/component): add sticky directive or component for position:sticky behavior https://github.com/valor-software/ngx-bootstrap/issues/1992
- [ ] feat(scrollspy): Is there any plan to add scrollspy? https://github.com/valor-software/ngx-bootstrap/issues/2623

### Existing issues
- [ ] fix(build): Error: Uncaught (in promise): TypeError: Class constructor Lh cannot be invoked without 'new' https://github.com/valor-software/ngx-bootstrap/issues/3252
- [x] fix(demo): console errors appears at demo on Safari browsers https://github.com/valor-software/ngx-bootstrap/issues/3305
- [ ] fix(demo): demo header is not static for safari browser https://github.com/valor-software/ngx-bootstrap/issues/3312
- [ ] fix(demo): For bootstrap 4 when cursor is hovered on disabled element it's style doesn't changed to cursor: not-allowed https://github.com/valor-software/ngx-bootstrap/issues/3369
- [ ] fix(demo): left sidebar is not fully visible on small screens https://github.com/valor-software/ngx-bootstrap/issues/3383
- [ ] fix(build): isBs3() function not work properly with chrome + unzoom + windows https://github.com/valor-software/ngx-bootstrap/issues/3446
- [ ] fix(build): Angular 5.2 ngc build produces node_modules folder with missing js files https://github.com/valor-software/ngx-bootstrap/issues/3458

## Component acceptance criteria:
- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
   - ngmodel
   - ngmodel + custom validation
   - reactive forms
   - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes

**Comment by netwobble** [comment]
I personally think that having nav bars should be a high priority and allow for quicker adoption.  Almost all projects will begin with a nav bar of some sort, and would be responsive. There are a few users that have opened issues and posted work around (I found one such workaround that enabled my container closing/opening). But I would have expected this to be there from day one. 

Also ....
Scrollspy is also a nice feature for starter web sites. 

Just my votes and opinions.

**Comment by valorkin** [comment]
Nav and side bars are first prio indeed ;)

**Comment by iagocaldeira** [comment]
I hope the animations also have a high priority in the list
