### ISSUE TITLE
roadmap(rating): aggregation issue

### ISSUE THREAD

**Issue by YevheniiaMazur** [valor-software/ngx-bootstrap#3468]
### Demos
- [ ] docs(rating): demos should have following structure
   - Quick start
   - Properties
   - Styling
   - Custom content
   - Config
- [ ] docs(rating): rename `Static rating` to `Basic` #3653

### New functionality
- [ ] feat(rating): add decimal support https://github.com/valor-software/ngx-bootstrap/issues/1437

### Existing issues
- [ ] fix(rating): rating titles change format part way through https://github.com/valor-software/ngx-bootstrap/issues/1751

## Component acceptance criteria:
- [ ] Adding to project / Quick start
  - note for system.js
  - node for lazy load and child modules
- [ ] Examples covering available options and events
- [ ] Forms:
   - ngmodel
   - ngmodel + custom validation
   - reactive forms
   - reactive forms + custom validation
- [ ] Each demo sample should have test
- [ ] Styling
  - via parent component
  - via global css
- [ ] Accessibility
  - Aria
  - Keyboard navigation
  - Mobile
- [ ] Animations support (from animation component)
- [ ] Overriding default config
  - for all project
- [ ] Custom templates (ngx-bootstrap components)
- [ ] Api Services & Api Directives
- [ ] Usage via services
- [ ] Usage via data attributes
