### ISSUE TITLE
feat(datepicker)

### ISSUE THREAD

**Issue by valorkin** [valor-software/ngx-bootstrap#817]
- [x] upgrade to rc.6
- [ ] time picker -> populate to active\selected\selected end dates (see date picker state class)
- [x] time picker -> show/hide AM/PM, on click +-12 hours
- [x] issue localization year range numbers
- [ ] options: add isPreview
- [ ] options: add date range separator option
- [ ] Implement auto Apply (add event to state)
- [ ] support ngModel + form control 
- [ ] support inline\popup version
- [x] fix Weeks Numbers

later:
- [ ] select week
- [ ] linked calendars
